### ISSUE TITLE
frontend-logging

### ISSUE THREAD

**Issue by deliczakir** [zijadlicina/Products-App#52]
- [x] uraditi frontend za logging
- [x] uraditi push koda
- [x] napraviti pull request

**Comment by zijadlicina** [comment]
![image](https://user-images.githubusercontent.com/97347415/170088855-d795e6b5-d772-4869-b17f-ffbd07eb8710.png)
Treba ispavka "logging" tabele.
Kada se doda vise usera, prvi user se ne vidi...
